Tesis/TesisAlarmas/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TesisAlarmas;

namespace TesisAlarmas.Controllers
{
    public class AlumnoController : Controller
    {
        private BD db = new BD();

        // GET: Alumno
        public ActionResult Index()
        {
            var alumno = db.alumno.Include(a => a.apoderado).Include(a => a.curso);
            return View(alumno.ToList());
        }
        

        // GET: Alumno/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            alumno alumno = db.alumno.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            return View(alumno);
        }

        // GET: Alumno/Create
        public ActionResult Create()
        {
            ViewBag.Apoderado_RUT = new SelectList(db.apoderado, "RUT", "Nombres");
            ViewBag.Curso_ID = new SelectList(db.curso, "ID", "Nivel");
            return View();
        }

        // POST: Alumno/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RUT,Nombres,Apellidos,Celular,Direccion,Email,Apoderado_RUT,Curso_ID,Ubicacion_ID")] alumno alumno)
        {
            if (ModelState.IsValid)
            {
                db.alumno.Add(alumno);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Apoderado_RUT = new SelectList(db.apoderado, "RUT", "Nombres", alumno.Apoderado_RUT);
            ViewBag.Curso_ID = new SelectList(db.curso, "ID", "Nivel", alumno.Curso_ID);
            return View(alumno);
        }

        // GET: Alumno/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            alumno alumno = db.alumno.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            ViewBag.Apoderado_RUT = new SelectList(db.apoderado, "RUT", "Nombres", alumno.Apoderado_RUT);
            ViewBag.Curso_ID = new SelectList(db.curso, "ID", "Nivel", alumno.Curso_ID);
            return View(alumno);
        }

        // POST: Alumno/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RUT,Nombres,Apellidos,Celular,Direccion,Email,Apoderado_RUT,Curso_ID,Ubicacion_ID")] alumno alumno)
        {
            if (ModelState.IsValid)
            {
                db.Entry(alumno).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Apoderado_RUT = new SelectList(db.apoderado, "RUT", "Nombres", alumno.Apoderado_RUT);
            ViewBag.Curso_ID = new SelectList(db.curso, "ID", "Nivel", alumno.Curso_ID);
            return View(alumno);
        }

        // GET: Alumno/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            alumno alumno = db.alumno.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            return View(alumno);
        }

        // POST: Alumno/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            alumno alumno = db.alumno.Find(id);
            db.alumno.Remove(alumno);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tesis/TesisAlarmas/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TesisAlarmas.Models;

namespace TesisAlarmas.Controllers
{
    public class CursoController : Controller
    {
        private BD db = new BD();

        // GET: Curso
        public ActionResult Index()
        {
            return View(db.curso.ToList());
        }

        // GET: Curso/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            curso curso = db.curso.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // GET: Curso/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Curso/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(curso curso, string Educacion)
        {
            bool validacion = curso.Validar(Educacion);

            if (validacion == true)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        db.curso.Add(curso);
                        db.SaveChanges();

                        ViewBag.MessageOK = "El curso " + curso.Nivel + "-" + curso.Division + " se ha agregado correctamente.";
                        return View();
                        //return RedirectToAction("Index");
                    }
                }
                catch(Exception ex)
                {
                    ViewBag.MessageError = "No se ha podido agregar el curso a la Base de Datos. <br/>El error es: "+ex;
                }
            }
            else
            {
                ViewBag.MessageEducacion = "Por favor seleccione un Tipo de Educación";
            }

            return View(curso);
        }

        public ActionResult ListaEducacion()
        {
            IQueryable educaciones = Educacion.GetEducaciones();

            if (HttpContext.Request.IsAjaxRequest())
            {
                return Json(new SelectList(
                            educaciones,
                            "EducacionCodigo",
                            "EducacionTipo"), JsonRequestBehavior.AllowGet
                            );
            }

            return View(educaciones);
        }

        public ActionResult ListaNivel(string EducacionCodigo)
        {
            IQueryable niveles = Nivel.GetNiveles().Where(x => x.EducacionCodigo == EducacionCodigo);

            if (HttpContext.Request.IsAjaxRequest())
                return Json(new SelectList(
                                niveles,
                                "NivelID",
                                "NivelNombre"), JsonRequestBehavior.AllowGet
                            );

            return View(niveles);
        }

        // GET: Curso/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            curso curso = db.curso.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Curso/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nivel,Division")] curso curso)
        {
            if (ModelState.IsValid)
            {
                db.Entry(curso).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(curso);
        }

        // GET: Curso/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            curso curso = db.curso.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Curso/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            curso curso = db.curso.Find(id);
            db.curso.Remove(curso);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tesis/TesisAlarmas/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TesisAlarmas;
using System.Net;
using System.Net.Mail;

namespace Tesis.Controllers
{
    public class UsuarioController : Controller
    {
        public ActionResult Menu()
        {
            return View();
        }

        public ActionResult Login()
        {
            if (Session["adminId"] != null)
            {
                return Redirect("/Home/About");
            }
            else
            {
                if(Session["apoderadoRUT"] != null)
                {
                    return Redirect("/Home/Contact");
                }
                return View();
            }
        }

        [HttpPost]
        public ActionResult Login(string Usuario, string Contrasena)
        {
            ViewBag.Usuario = Usuario.Trim();
            ViewBag.Contrasena = Contrasena.Trim();

            if ((Usuario != null && Usuario != "") && (Contrasena != null && Contrasena != ""))
            {
                try
                {
                    var administrador = new administrador();

                    administrador busqueda1 = administrador.LoginAdministrador(Usuario, Contrasena);
                    if (busqueda1 != null)
                    {
                        Session.Add("AdminID", busqueda1.ID);
                        Session.Add("UsuarioNombre", busqueda1.Usuario);
                        Session.Add("Rol", "Administrador");
                        return Redirect("/Usuario/Menu");
                    }
                    else
                    {
                        var apoderado = new apoderado();

                        apoderado busqueda2 = apoderado.LoginApoderado(Usuario, Contrasena);
                        if (busqueda2 != null)
                        {
                            Session.Add("ApoderadoRUT", busqueda2.RUT);
                            Session.Add("UsuarioNombre", busqueda2.Nombres);
                            Session.Add("UsuarioApellido", busqueda2.Apellidos);
                            Session.Add("Rol", "Apoderado");
                            return Redirect("/apoderados/Menu");
                        }
                        else
                        {
                            ViewBag.MessageError = "Error al ingresar datos";
                        }
                    }
                }
                catch (Exception errorlogin)
                {
                    ViewBag.MessageError = "Ha ocurrido un error: " + errorlogin;
                }
            } 
            else
            {
                    ViewBag.MessageError = "Por favor ingrese datos";
            }
            return View();
        }



        public ActionResult Recuperar()
        {
            ViewBag.Message = "Email";

            return View();
        }

        [HttpPost]
        public ActionResult Recuperar(string Correo)
        {
            ViewBag.Correo = Correo;

            var apoderado = new apoderado();
            apoderado contrasena = apoderado.RecuperarContra(Correo);
            var mmsg = new MailMessage();
            mmsg.To.Add(new MailAddress(Correo));
            mmsg.Body = "Señor/a "+contrasena.Nombres+" "+contrasena.Apellidos+" su contraseña es: "+contrasena.Contrasena;
            mmsg.Subject = "Recuperación de contraseña";
            mmsg.SubjectEncoding = System.Text.Encoding.UTF8;
            mmsg.From = new MailAddress("m1m2m3m4m5@outlook.com");
            mmsg.IsBodyHtml = true;

            using (var cliente = new SmtpClient())
            {
                try
                {
                    cliente.Send(mmsg);
                    return Redirect("/Usuario/Login");
                }
                catch (SmtpException ex)
                {
                    ViewBag.Message = "Ha ocurrido un error: " + ex;
                }
            }
            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return Redirect("/Usuario/Login");
        }
    }
}

Tesis/TesisAlarmas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

        @if (Convert.ToString(Session["Rol"]) == "Administrador")
            {
                <div class="navbar navbar-inverse navbar-fixed-top">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            @Html.ActionLink("Menu", "Index", "Home", null, new { @class = "navbar-brand" })
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Crear<span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>@Html.ActionLink("Crear Alummos", "Create", "Alumno")</li>
                                        <li>@Html.ActionLink("Crear Apoderados", "Create", "apoderados")</li>
                                        <li>@Html.ActionLink("Crear Curso", "Create", "Curso")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Listar<span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>@Html.ActionLink("Listar Elementos", "ListarElementos", "Usuario")</li>
                                        <li>@Html.ActionLink("Listar Marcaciones", "ListarMarcaciones", "Alumno")</li>
                                    </ul>
                                </li>
                                <li><a>Editar</a></li>
                                <li><a>Ver Ubicación</a></li>
                                <li><a href="~/Alumno/AsignarCurso">Asignar Curso</a></li>
                            </ul>
                            @if (!Session.IsNewSession)
                            {
                                <div style="float:right; margin-top: 15px;"><a href="~/Usuario/Logout" style="color: #FFFFFF">Cerrar sesión</a></div>
                                <div></div>
                                <div style="text-align:center; margin-top: 15px;"><p style="color: #FFFFFF">Usuario actual: @Session["UsuarioNombre"]</p></div>
                            }
                        </div>
                    </div>
                </div>
            }
            @if (Convert.ToString(Session["Rol"]) == "Apoderado")
            {
                <div class="navbar navbar-inverse navbar-fixed-top">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            @Html.ActionLink("Menú", "Menu", "apoderados", null, new { @class = "navbar-brand" })
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li><a>Ver Ubicación</a></li>
                                <li><a>Editar</a></li>
                                <li><a>Listar Marcaciones</a></li>
                                <li><a>Configurar Horario</a></li>
                                <li><a>Alarmas Recibidas</a></li>
                            </ul>
                            @if (!Session.IsNewSession)
                            {
                                <div style="float:right; margin-top: 15px;"><a href="~/Usuario/Logout" style="color: #FFFFFF">Cerrar sesión</a></div>
                                <div></div>
                                <div style="text-align:center; margin-top: 15px;"><p style="color: #FFFFFF">Usuario actual: @Session["UsuarioNombre"]</p></div>
                            }
                        </div>
                    </div>
                </div>
            }
            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
                </footer>
            </div>
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
</body>
</html>